name: 🚀 Node.js CI with Docker

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test echo
      run: echo "Hello, World!"

    - name: print working directory
      run: pwd

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: print working directory
      run: pwd
    


