name: 🚀 Node.js CI with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test echo
        run: echo "Hello, World!"

      - name: print working directory (before checkout)
        run: pwd && ls

      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files (after checkout)
        run: |
          echo "✅ Code after checkout:"
          ls -l 

      - name: print working directory (after checkout)
        run: pwd && ls
